---
title: "Chapter 4 problems"
author: "Stephen R. Proulx"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())

```

```{r 4M1}

mu <- rnorm(1,mean=0, sd=10)
sigma <- rexp(n=1, rate=1)
data <- tibble(y=rnorm(1000,mean=mu, sd=sigma))

ggplot(data=data , aes(x=y)) + geom_histogram() 
```


Question 4M2, stan style
```{r write_stan}
sink("Q4M2.stan")
cat("
data{
  int k ; // the number of data points
  real y[k] ; // the data as a vector of length k
}
parameters {
  real mu ; // define the parameter mu
  real <lower=0> sigma ; // define the parameter sigma, noting that it has a lower bound of zero
}
model{
mu ~ normal(0,10) ; // set the prior for mu
sigma ~ exponential(1) ; // set the prior for sigma
y ~ normal(mu,sigma) ; // calculate the likelihood of the data, y, given the parameters, mu and sigma
}    
    
", fill=TRUE) 
sink()

```

```{ r 4M2-stan}

model <- stan_model(file="Q4M2.stan") # Compile the stan program
 
 
stan_data <-list(k=nrow(data) ,  y= data$y) 
                 
fit_y <- sampling(model, data = stan_data , chains=4, iter=1000, seed = 23423423)

print(fit_y)

```

fit a smaller set of data
```{r fit_smaller}
data_sub=sample_n(data,10)
stan_data <-list(k=nrow(data_sub) ,  y= data_sub$y) 
     
fit_y_sub <- sampling(model, data = stan_data , chains=4, iter=1000, seed = 23423423)

print(fit_y_sub)

```